name: Workflow Master

on:
  push:
    branches:    
      - master

jobs:
  workflow:
    runs-on: ubuntu-latest
    permissions: write-all
    concurrency: staging_environment
    steps:   
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'zulu'
          server-id: github-pieter-commons        
              
      - name: Build with Maven
        run: mvn -B package --file pom.xml